### ISSUE TITLE
ministers en stassen?

### ISSUE THREAD

**Issue by steflommen** [openkamer/openkamer#16]
I think we should include the ministers and stassen also in openkamer, preferably the both as a person as well as the position. Stricly speaking they are not a member of parliament, yet they do closely cooperate with them.

Including them should make it way easier to track the actions of a certain minister as well as get a complete overview of a persons activities in both parliament and government.

**Comment by bartromgens** [comment]
Yes! And indeed important to separate the person from the position. 

A first idea for a rather flexible data structure that separates the roles and allows for multiple governments, and multiple persons at a position for a single government. 

Government
- name
- start_date
- end_date

Ministry (Department?)
- name
- government (Government)

GovernmentPosition
- name/type [prime minister, minister, staatssecretaris]
- ministry (Ministry)

GovernmentMember
- person (Person)
- position (GovernmentPosition)
- start_date
- end_date

The limitation here is that each government (Rutte II) has new a new ministry and position (Minister of Justice) , and these positions are not directly linked (only by name). So the position of Minister of Justice in Rutte I is not directly linked (or the same) as the Minister of Justice in Rutte II.  
Is this a problem or a good thing?

**Comment by steflommen** [comment]
There are benefits to this structure, as the content of a position is not constant over different governments. Such structure can deal with this. 

Some linking would be good for users, although it is not essential that its directly linked.

**Comment by bartromgens** [comment]
I suggest to get the data of current and previous governments, ministries, ministers and stassen from http://www.wikidata.org. Wikidata is not at all complete in this area, but we will only have to add it once (manually), and we and everyone else can benefit forever. 

The current cabinet can serve as example: https://www.wikidata.org/wiki/Q1638648

Data can be found at http://www.parlement.com, for example here: http://www.parlement.com/id/vg6gfs1frizd/selectiemenu_bewindspersonen
Scraping parlement.com for this data is not so easy. Might be most efficient to do it manually. Not fun though.

**Comment by bartromgens** [comment]
I just completed Rutte II, including stassen on wikidata: https://www.wikidata.org/wiki/Q1638648
Took me 30 minutes.

A list of previous cabinets:
- [x] Kabinet-Rutte II (2012-now) - http://www.parlement.com/id/vj47glycfix9/kabinet_rutte_ii_2012_heden
- [ ] Kabinet-Rutte I (2010-2012) - http://www.parlement.com/id/vij7e8jky5lw/kabinet_rutte_i_2010_2012
- [ ] Kabinet-Balkenende IV (2007-2010) - http://www.parlement.com/id/vhnnmt7mqgzh/kabinet_balkenende_iv_2007_2010
- [ ] Kabinet-Balkenende III (2006-2007) - http://www.parlement.com/id/vhnnmt7m2000/kabinet_balkenende_iii_2006_2007
- [ ] Kabinet-Balkenende II (2003-2006) - http://www.parlement.com/id/vhnnmt7jpazy/kabinet_balkenende_ii_2003_2006
- [ ] Kabinet-Balkenende I (2002-2003) - http://www.parlement.com/id/vh8lnhrpfxup/kabinet_balkenende_i_2002_2003
- [ ] Kabinet-Kok II (1998-2002) - http://www.parlement.com/id/vh8lnhronvx4/kabinet_kok_ii_1998_2002
- [ ] Kabinet-Kok I (1994-1998) - http://www.parlement.com/id/vh8lnhronvvu/kabinet_kok_i_1994_1998

**Comment by bartromgens** [comment]
The basic data model, as discussed above, and some basic tests, views and templates are now active with the merge of the `feature/government` branch in commit f180376f243e43bb214f0ca379111e6831e0ad38.

All government models are created from wikidata.org data. Initials (name) of government members are taken from parlement.com. 

The political party of government members is now also shown, including link, as demonstration of the linked data. 

To get previous governments into openkamer, we need to complete them on wikidata.org, in a similar way as for Rutte-II (https://www.wikidata.org/wiki/Q1638648, see 'has part'). See the checklist in my post above. Take data from http://www.parlement.com.

![government_page_preview](https://cloud.githubusercontent.com/assets/2451596/19618854/5d09a86a-9856-11e6-8276-bb4b41eefae4.png)

**Comment by bartromgens** [comment]
I have created a new issue for adding data to wikidata.org: issue #22. 
I will close this issue because the basic government model and scraper is finished.
