### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bartromgens** [openkamer/openkamer#21]
openkamer is intended to be an open source (FOSS) project. However, the source code is currently public, but without license the copyright is still with the creators and is not a FOSS project.

We should pick an open source license to make this project a real open source project. 

There are basically two options:
- a [copyleft](https://www.gnu.org/licenses/copyleft.en.html) license that forces users and/or modifications to use the same free license, example is the GPL license
- a very liberal license that allows everything including commercial use, example is MIT license

**Comment by bartromgens** [comment]
I'm leaning towards the [MIT license](https://opensource.org/licenses/MIT) because it is very simple and permissive. However, it does allow others to profit from openkamer without sharing their use or modifications. I don't mind others to profit, but I prefer they share their modifications. In practice, however, I believe having to share code means it is less likely others (commercial users) will use it. 

@steflommen, is MIT ok for you? Without license, you have copyright and all rights on the code you wrote.

**Comment by steflommen** [comment]
yes that's fine with me.

**Comment by bartromgens** [comment]
Ok. It's done, see https://github.com/openkamer/openkamer/blob/master/LICENSE.md

No way back :) 

openkamer is now truly FOSS! \o/
