### ISSUE TITLE
Get all (including inactive) parliament members

### ISSUE THREAD

**Issue by bartromgens** [openkamer/openkamer#24]
Parliament members are currently scraped from a list of active members on tweedekamer.nl.

However, documents etc will contain members who are not active anymore. These should still be listed and linked etc, just as inactive parliament member. 

tweedekamer.nl does not seem to provide this list of inactive members. www.parlement.com or www.wikidata.org may be good sources, but there may be others. These need to be scraped.

**Comment by bartromgens** [comment]
Note that www.parlement.com has copyright on all their content. We need permission before we can use it.

**Comment by bartromgens** [comment]
I sent an email to parlement.com asking for permission, and possible terms, of using their historic data on parliament members (names and dates). 

I believe it is important that all openkamer data is free and open to use for everyone, for any purpose. If they cannot give that permission, we have to find a different source (manually add it to wikidata.org).

**Comment by bartromgens** [comment]
parlement.com is reluctant to let us use their parliament member data (name, start/end date, party), although I am waiting for a final verdict. 

We might have to add this data, from some open source, to wikidata.org. I believe it is something that should be publicly available and therefore worth the effort if this list is not in the public domain yet.

I had a brief discussion with wikidata users on IRC. They support this effort and some are willing to support and/or contribute.

I will contact de Tweede Kamer about this data. They should have this in some format.

**Comment by bartromgens** [comment]
I sent a contact form/email to the Tweede Kamer. Let's hope they have this data.

**Comment by bartromgens** [comment]
I have manually completed all parliament members with start/end dates on wikidata since the elections of 2006, based on wikipedia info. Also wrote checks to make sure it is complete.

**Comment by bartromgens** [comment]
As of today, 11 office days since my emai/contact form, still no reaction from the Tweede Kamer. Just sent them a notification because they say to answer within 3-5 office days.

**Comment by bartromgens** [comment]
The Tweede Kamer replied. The data is not available due to technical reasons ('informatie technische redenen').

I have replied to ask for confirmation that they indeed do have the data, but that it is only not available for some technical reason. If so, how hard can it be :) ?

**Comment by steflommen** [comment]
I am quite curious about this technical issue, this sounds a bit odd.

**Comment by bartromgens** [comment]
The Tweede Kamer simply doesn't have this information. The 'technical reasons' is just an excuse because they are ashamed to admit that they don't have it. 

We will have to do with wikidata and parliament.com. 

OpenKamer currently uses wikidata for parliament members so I consider this closed.
