### ISSUE TITLE
Timeline wetsvoorstel

### ISSUE THREAD

**Issue by bartromgens** [openkamer/openkamer#3]

**Comment by bartromgens** [comment]
Here is a nice vertical responsive timeline that we could use: 
- demo: https://codyhouse.co/demo/vertical-timeline/index.html
- article and download: https://codyhouse.co/gem/vertical-timeline/

This works nicely on desktop and mobile. 

These vertical timelines are usually not to scale; the distance between events on the timeline does not indicate the time between those events. We would probably get lots of empty space anyway when we make the timeline to scale.

**Comment by bartromgens** [comment]
Some horizontal timelines that we could use for true time scale:
- https://timeline.knightlab.com/ : fancy, well maintained, date ranges, stacked items, zoom and pan, works on mobile
- https://kri.gs/eventcontrol/ : simple, stacked items, no date ranges

**Comment by steflommen** [comment]
I like this! clean and easy.

Making the timeline to scale is imho not necessary. Indeed lots of empty space or cluttered segments when several documents are released around the same date.
Although it could be nice to add a bit of space if there it there is >3 months in between.
