### ISSUE TITLE
Show interesting (featured) wetsvoorstellen on top of the wetsvoorstellen page

### ISSUE THREAD

**Issue by bartromgens** [openkamer/openkamer#43]
Wetsvoorstellen on `/wetsvoorstellen/`are ordered by date. This means that only new items are shown on this page. However, new items do not demonstrate the features of openkamer because they typically do not contain any votings, discussions or other related documents or results yet. 

To demonstrate the features of openkamer to new visitors, it would be nice to show a few links to older wetsvoorstellen. These should ideally be picked by a simple algorithm that is not content aware, to make sure openkamer stays independent.

**Comment by steflommen** [comment]
We can feature wetsvoorstellen which have recently seen votings?

**Comment by bartromgens** [comment]
Yes! 

The latest 4 (default, can be set via `NUMBER_OF_LATEST_DOSSIERS` in `local_settings.py`) wetsvoorstellen that have been voted on are now shown on top of the page, below the filter form. 

The filter also acts on these 'latest' wetsvoorstellen. 

Implemented in dd2b379.

**Comment by bartromgens** [comment]
This change is deployed @ http://www.openkamer.org/wetsvoorstellen/
